networks:
  coolify:
    external: true

volumes:
  n8n_storage:
  postgres_storage:
  ollama_storage:
  qdrant_storage:

services:
  # PostgreSQL
  postgres:
    image: postgres:15
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: prince
      POSTGRES_PASSWORD: prince
      POSTGRES_DB: prince
    volumes:
      - postgres_storage:/var/lib/postgresql/data
    networks:
      - coolify

  # n8n
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      DB_TYPE: postgresdb
      DB_POSTGRESDB_HOST: postgres
      DB_POSTGRESDB_PORT: 5432
      DB_POSTGRESDB_DATABASE: prince
      DB_POSTGRESDB_USER: prince
      DB_POSTGRESDB_PASSWORD: prince
      N8N_HOST: n8n.local
      N8N_PORT: 5678
      N8N_BASIC_AUTH_ACTIVE: "true"
      N8N_BASIC_AUTH_USER: admin
      N8N_BASIC_AUTH_PASSWORD: password
      N8N_ENCRYPTION_KEY: super-prince-key
      N8N_USER_MANAGEMENT_JWT_SECRET: even-prince-secret
      N8N_DEFAULT_BINARY_DATA_MODE: filesystem
    volumes:
      - n8n_storage:/home/node/.n8n
    depends_on:
      - postgres
    networks:
      - coolify

  # Vector DB (Qdrant)
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    volumes:
      - qdrant_storage:/qdrant/storage
    ports:
      - "6333:6333"
    networks:
      - coolify

  # Pull deepseek model (runs once)
  ollama-pull-deepseek-cpu:
    image: ollama/ollama:latest
    container_name: ollama-pull-deepseek-cpu
    profiles: ["cpu"]
    entrypoint: ["/bin/sh", "-c"]
    command: ["ollama pull deepseek-r1:1.1b && echo 'Model pulled successfully'"]
    volumes:
      - ollama_storage:/root/.ollama
    networks:
      - coolify
    dns:
      - 8.8.8.8
      - 8.8.4.4
      - 1.1.1.1
    extra_hosts:
      - "registry.ollama.ai:104.21.15.34"
      - "ollama.ai:104.21.15.34"

  # Ollama runtime (CPU)
  ollama-cpu:
    image: ollama/ollama:latest
    container_name: ollama-cpu
    profiles: ["cpu"]
    ports:
      - "11434:11434"
    volumes:
      - ollama_storage:/root/.ollama
    networks:
      - coolify
    dns:
      - 8.8.8.8
      - 8.8.4.4
      - 1.1.1.1
    extra_hosts:
      - "registry.ollama.ai:104.21.15.34"
      - "ollama.ai:104.21.15.34"
